name: update_helper
description: Help you easier to control the update dialog. It also supports the feature that forces the app to update to continue using.
version: 0.5.2
homepage: https://github.com/vnniz/update_helper

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^4.0.2
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.14
  satisfied_version: ^0.3.0
  http: ^1.1.0
  boxw: ^0.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
